/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: inciprocal (https://sketchfab.com/inciprocal.com)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-lowa-gore-tex-boot-2021-free-417531d1bfcd4fc39f9cedbc1c85963e
Title: Old Lowa Gore-Tex Boot (2021 / FREE)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/gltf/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.sh_lowaTibetGT}
        rotation={[-Math.PI / 2, 0, -0.506]}
      />
    </group>
  );
}
