/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 bearpaw.glb 
Author: inciprocal (https://sketchfab.com/inciprocal.com)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bearpaw-hq-free-df3419882aaa41f8bcdb7cbe90e27d5c
Title: Bearpaw HQ (FREE)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/bearpaw/bearpaw.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        position={[1, 1.8, -2]}
        scale={40}
        castShadow
        geometry={nodes.Object_2.geometry}
        material={materials.sh_bearPawBootHQ}
        rotation={[-Math.PI / 2, -Math.PI * 2, 0]}
      />
    </group>
  );
}
